app/src/main/java/me/rocka/fcitx5test/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
add a button and some text to guide the user to enable fcitx
=> add guide button to launch IME settings activity

app/src/main/java/me/rocka/fcitx5test/SettingsActivity.kt
No icon space.
Permit multi-line titles.
=> minor tweaks in Settings UI

app/src/main/AndroidManifest.xml, app/src/main/java/me/rocka/fcitx5test/FcitxDaemon.kt, app/src/main/java/me/rocka/fcitx5test/FcitxService.kt, app/src/main/java/me/rocka/fcitx5test/KeyboardPresenter.kt, app/src/main/java/me/rocka/fcitx5test/MainActivity.kt, app/src/main/java/me/rocka/fcitx5test/SettingsActivity.kt, app/src/main/java/me/rocka/fcitx5test/Utils.kt, app/src/main/java/me/rocka/fcitx5test/native/Fcitx.kt, app/src/main/java/me/rocka/fcitx5test/native/FcitxLifecycle.kt
So far, there is at most one component binding to FcitxDaemon though
=> Add FcitxDaemon to manage fcitx instance

app/build.gradle.kts, nix/default.nix, nix/sdk.nix, shell.nix
In nix shell
* Use `$NDK_VERSION` as NDK version 
* Overwrite `local.properties` to use Android SDK from nixpkgs
=> Fix nix shell

.gitignore, app/build.gradle.kts, app/src/main/java/me/rocka/fcitx5test/AppSharedPreferences.kt, app/src/main/java/me/rocka/fcitx5test/Const.kt, app/src/main/java/me/rocka/fcitx5test/MainFragment.kt, app/src/main/java/me/rocka/fcitx5test/Utils.kt, app/src/main/java/me/rocka/fcitx5test/asset/AssetManager.kt, app/src/main/java/me/rocka/fcitx5test/asset/Types.kt, app/src/main/java/me/rocka/fcitx5test/native/Fcitx.kt, app/src/main/res/values/strings.xml
* Sync entire assets to data directory on fcitx startup
* Remove `ASSETS_VERSION`
=> Sync data dir with assets automatically

app/src/main/AndroidManifest.xml, app/src/main/java/me/rocka/fcitx5test/ui/setup/SetupActivity.kt, app/src/main/java/me/rocka/fcitx5test/ui/setup/SetupFragment.kt, app/src/main/res/values/strings.xml
Also make the constructor of `SetupFragment` nullary, in order to fix the crash when screen rotates
=> Send notification when not setup

app/src/main/java/org/fcitx/fcitx5/android/ui/common/BaseDynamicListUi.kt
https://github.com/material-components/material-components-android/issues/851#issuecomment-769752413
=> Improve fab behavior

app/src/main/java/org/fcitx/fcitx5/android/data/theme/CustomThemeSerializer.kt, app/src/main/java/org/fcitx/fcitx5/android/data/theme/Theme.kt, app/src/main/java/org/fcitx/fcitx5/android/data/theme/ThemeManager.kt, app/src/main/java/org/fcitx/fcitx5/android/data/theme/ThemePreset.kt, app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/popup/PopupEntryUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/popup/PopupKeyboardUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/status/StatusAreaEntryUi.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/settings/theme/ThemeListFragment.kt, app/src/main/java/org/fcitx/fcitx5/android/utils/NostalgicSerializer.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/fcitx/fcitx5/android/ThemeSerializationTest.kt
- `popup{Background,Text}Color`
- `genericActive{Back,Fore}groundColor`
=> Add some new theme properties

app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/TextKeyboard.kt, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Add option to keep keyboard letters uppercase

app/build.gradle.kts, app/src/main/java/org/fcitx/fcitx5/android/FcitxApplication.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/LogActivity.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/log/LogAdapter.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/log/LogView.kt, flake.lock, flake.nix
replaces `cat.ereza:customactivityoncrash`
=> Custom UncaughtExceptionHandler

.github/workflows/fdroid.yml, app/org.fcitx.fcitx5.android.yml
I uses yq to patch the metadata in fdroiddata to build from master. This is hacky. Anyway you need to update the metadata sometimes. Maybe it's better to add a template in this repo.
It's triggered everyday currently.
=> Add fdroid build workflow

app/src/main/java/org/fcitx/fcitx5/android/data/InputFeedbacks.kt, app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt, app/src/main/java/org/fcitx/fcitx5/android/data/prefs/ManagedPreference.kt, app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/CandidateItemUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CustomGestureView.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDefPreset.kt, app/src/main/java/org/fcitx/fcitx5/android/utils/SystemService.kt, app/src/main/java/org/fcitx/fcitx5/android/utils/Utils.kt, app/src/main/res/values/strings.xml, flake.nix
Closes #279, as the support for customized sound effects is not planned for now
=> Add sound effects on key press

.github/workflows/fdroid.yml, app/org.fcitx.fcitx5.android.yml
Try to fix F-Droid build error
```
ERROR: Found unknown maven repo 'https://maven.pkg.github.com/fcitx5-android/fcitx5-android' at lib/plugin-base/build.gradle.kts
ERROR: Found unknown maven repo 'https://maven.pkg.github.com/fcitx5-android/fcitx5-android' at lib/common/build.gradle.kts
```
by replacing publish uri to jitpack.io
N/A
TBD.
=> Replace publish uri before F-Droid build

.github/workflows/pull_request.yml, README.md, lib/fcitx5/src/main/cpp/cmake/FindECM.cmake
=> Add Windows CI

app/src/main/res/values/strings.xml
Fix English strings (most of them are typos or grammar mistakes).
=> Fix some English strings

app/src/main/cpp/androidfrontend/androidfrontend.cpp, app/src/main/cpp/androidfrontend/androidfrontend.h, app/src/main/cpp/androidfrontend/androidfrontend_public.h, app/src/main/cpp/helper-types.h, app/src/main/cpp/jni-utils.h, app/src/main/cpp/native-lib.cpp, app/src/main/cpp/object-conversion.h, app/src/main/java/org/fcitx/fcitx5/android/core/Fcitx.kt, app/src/main/java/org/fcitx/fcitx5/android/core/FcitxAPI.kt, app/src/main/java/org/fcitx/fcitx5/android/core/Types.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/CandidateItemUi.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/CandidateViewHolder.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/HorizontalCandidateComponent.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/adapter/GridPagingCandidateViewAdapter.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/adapter/HorizontalCandidateViewAdapter.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/adapter/PagingCandidateViewAdapter.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/expanded/window/BaseExpandedCandidateWindow.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/expanded/window/FlexboxExpandedCandidateWindow.kt, app/src/main/java/org/fcitx/fcitx5/android/input/candidates/expanded/window/GridExpandedCandidateWindow.kt, app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CustomGestureView.kt
The [real "candidate action" API](https://github.com/fcitx/fcitx5/pull/1025) mentioned in https://github.com/fcitx5-android/fcitx5-android/pull/457#issuecomment-2042043564
=> Adopt fcitx5 candidate action API

.idea/dictionaries/project.xml, app/src/main/cpp/androidfrontend/androidfrontend.cpp, app/src/main/cpp/androidfrontend/androidfrontend.h, app/src/main/cpp/androidfrontend/androidfrontend_public.h, app/src/main/cpp/helper-types.h, app/src/main/cpp/jni-utils.h, app/src/main/cpp/native-lib.cpp, app/src/main/cpp/object-conversion.h, app/src/main/java/org/fcitx/fcitx5/android/core/Fcitx.kt, app/src/main/java/org/fcitx/fcitx5/android/core/FcitxAPI.kt, app/src/main/java/org/fcitx/fcitx5/android/core/FcitxEvent.kt, app/src/main/java/org/fcitx/fcitx5/android/input/CandidatesView.kt, app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt, app/src/main/java/org/fcitx/fcitx5/android/input/InputView.kt, app/src/main/java/org/fcitx/fcitx5/android/input/preedit/PreeditUi.kt, app/src/main/java/org/fcitx/fcitx5/android/utils/InputConnection.kt
=> Show floating CandidatesView for hardware keyboard

.github/workflows/nix.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, app/src/main/AndroidManifest.xml, app/src/main/java/org/fcitx/fcitx5/android/data/theme/Theme.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/CropImageActivity.kt, app/src/main/java/org/fcitx/fcitx5/android/ui/main/settings/theme/CustomThemeActivity.kt, app/src/main/java/org/fcitx/fcitx5/android/utils/Menu.kt, app/src/main/res/drawable/ic_baseline_flip_24.xml, app/src/main/res/drawable/ic_baseline_rotate_right_24.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml, build-logic/convention/src/main/kotlin/AndroidAppConventionPlugin.kt, build-logic/convention/src/main/kotlin/AndroidPluginAppConventionPlugin.kt, build-logic/convention/src/main/kotlin/BuildMetadataPlugin.kt, build-logic/convention/src/main/kotlin/FcitxComponentPlugin.kt, build-logic/convention/src/main/kotlin/Utils.kt, build-logic/convention/src/main/kotlin/Versions.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Gradle 8.10.2, AGP 8.7.0
Migrate off https://github.com/CanHub/Android-Image-Cropper 's built-in CropImageActivity: https://github.com/CanHub/Android-Image-Cropper/pull/635
=> Update dependencies and migrate deprecations

.github/workflows/fdroid.yml, .github/workflows/nix.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, .gitmodules, app/org.fcitx.fcitx5.android.yml, app/src/main/cpp/CMakeLists.txt, build-logic/convention/src/main/kotlin/Versions.kt, flake.lock, flake.nix, gradle/libs.versions.toml, lib/fcitx5-chinese-addons/src/main/cpp/CMakeLists.txt, lib/fcitx5/src/main/cpp/CMakeLists.txt, lib/libime/src/main/cpp/CMakeLists.txt, lib/libime/src/main/cpp/cmake/FindLibIMECore.cmake, lib/libime/src/main/cpp/cmake/FindLibIMEPinyin.cmake, lib/libime/src/main/cpp/cmake/FindLibIMETable.cmake, plugin/jyutping/src/main/cpp/CMakeLists.txt, plugin/rime/src/main/cpp/CMakeLists.txt
AGP 8.9.1
Kotlin 2.1.20
CMake 3.31.1
NDK 28.0.13004108
=> Update to NDK r28 (C++20)

app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt, app/src/main/java/org/fcitx/fcitx5/android/input/CandidatesView.kt, app/src/main/res/values/strings.xml
add candidate window round corner support
for #704
=> add candidate window round corner support
